### ISSUE TITLE
Prediction above capacity

### ISSUE THREAD

**Issue by peterdudfield** [SheffieldSolar/PV_Live-API#23]
Just noticed this small bug, the `predicted` valued is above the `installedcapacity_mwp`
```
from pvlive_api import PVLive
pvl = PVLive()
pvl.latest(entity_type="gsp", entity_id=130,extra_fields='installedcapacity_mwp')
(130, '2023-06-20T11:00:00Z', 1.91197, 1.883053)
```

I'm not sure how common this is, but I thought I would just flag it

**Comment by JamieTaylor-TUOS** [comment]
Hi Peter,

I've not spotted this before in PV_Live data, but it is theoretically possible...

The `installed capacity` (a.k.a. `nominal capacity`) is not the maximum generation a PV module/system can achieve - it is the expected output under [Standard Test Conditions (STC)](https://en.wikipedia.org/wiki/Solar_panel#:~:text=Performance%20and%20degradation%5Bedit%5D).

If the conditions throughout a given half-hour are more optimal than the STC (i.e. irradiance greater than 1000 W/m2 plus low ambient temperature plus cooling wind), then the PV generation would be expected to exceed the nominal capacity.

Its rare for this to occur in GB and unlikely that the phenomenon would affect an entire GSP region over a full half-hour, but not impossible. I'll leave this issue open until I'm able to access weather observations for that day/location and assess whether this might explain what you've seen.

Cheers
Jamie

**Comment by peterdudfield** [comment]
Thanks @JamieTaylor-TUOS for this. 

I was more thinking there could be a pv system reporting values alot higher than its nomial power. For example is someone doubled their array size.

**Comment by JamieTaylor-TUOS** [comment]
Ah I see! This _shouldn't_ be possible because we run all sample generation readings through a filter to remove any anomalous data. The upper limit includes a simulation of the maximum generation possible for each system under clear sky conditions i.e. we simulate clear sky irradiance at the location of each sample system and assume 120% performance ratio. Also, since each GSP's yield is modelled using at least 50 sample systems, it shouldn't be possible for 1 system to influence the modelled yield to this degree... I'll double check this though.
